#!/bin/bash
CONSUL=192.168.99.100

$(../../consul-template -consul $CONSUL:8500 -template "zkconnect.ctmpl:zkconnect.txt" -once)
ADDR_PORT="(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?):(\d?){5}"
ADDRS=$(grep -E -o $ADDR_PORT zkconnect.txt | awk '{print $1}' | paste -s -d, -)
echo $ADDRS